# Generated by Django 2.0rc1 on 2017-12-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrwellWeb', '0002_auto_20171201_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='gpu_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='processor_number',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='ram_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
